In [33]:
import numpy as np
import pandas as pd

In [34]:
data = pd.read_csv("/content/Titanic-Dataset.csv")

In [35]:
data = data.select_dtypes(include=['int64', 'float64'])
data.head()

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0            1         0       3  22.0      1      0   7.2500
1            2         1       1  38.0      1      0  71.2833
2            3         1       3  26.0      0      0   7.9250
3            4         1       1  35.0      1      0  53.1000
4            5         0       3  35.0      0      0   8.0500

In [36]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Age            177
SibSp            0
Parch            0
Fare             0
dtype: int64

In [39]:
data.fillna({'Age': data['Age'].mean()}, inplace=True)

In [40]:
x = data.drop('Survived', axis=1)
y = data['Survived']

In [43]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

Training KNN without Feature Scaling

In [44]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [46]:
ypred = knn.predict(x_test)

In [47]:
from sklearn.metrics import accuracy_score

In [50]:
print("accuracy score without featurescaling is :",accuracy_score(ypred, y_test))

accuracy score without featurescaling is : 0.5865921787709497

Training KNN with Featuring Scaling

In [51]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [52]:
knn2 = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train_scaled, y_train)

KNeighborsClassifier(n_neighbors=3)

In [53]:
ypred2 = knn.predict(x_test_scaled)

In [54]:
print("accuracy score with feature scaling is", accuracy_score(ypred2, y_test))

accuracy score with feature scaling is 0.7039106145251397